// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// DPLOOP
NumericVector DPLOOP(NumericVector p, NumericVector id);
RcppExport SEXP PopSV_DPLOOP(SEXP pSEXP, SEXP idSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type id(idSEXP);
    __result = Rcpp::wrap(DPLOOP(p, id));
    return __result;
END_RCPP
}
